
name: 'Heroku-deploy'
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: permissions
        run:
          chmod ${{ github.workspace }}/reports/ 777
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v0.1
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports/
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
            name: reports
            path: ${{ github.workspace }}/reports/
